# Generated by Django 2.2 on 2021-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(default='', max_length=254, unique=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='image',
            name='local_path',
            field=models.CharField(default='', max_length=254, unique=True, verbose_name='本地路径'),
        ),
    ]
