# Generated by Django 2.2 on 2021-02-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('other_classify', models.CharField(default='', max_length=511, verbose_name='top2-n的分类')),
                ('pred', models.CharField(default='', max_length=31, verbose_name='top1的置信度')),
                ('other_pred', models.CharField(default='', max_length=1023, verbose_name='top2-n的置信度')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态信息')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Category', verbose_name='分类')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='图片')),
            ],
            options={
                'verbose_name': '标注表',
            },
        ),
    ]
