# Generated by Django 2.2 on 2021-02-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210222_1745'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('classify', 'img')},
        ),
    ]
