# Generated by Django 2.2 on 2021-02-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20210222_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='pred',
            field=models.CharField(db_index=True, default='', max_length=31, verbose_name='top1的置信度'),
        ),
    ]
